# Generated by Django 6.0 on 2026-08-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo1', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='karma',
            field=models.IntegerField(default=50),
        ),
    ]
